project/app/urls.py
from django.urls import path, include
from .views import *

urlpatterns = [
    path("", home, name="home"),
    path("course/<str:slug>", coursepage, name="coursepage"),
    path("signup/", signup, name="signup"),
    path("login/", login, name="login"),
    path("check-out/<str:slug>", check_out, name="check-out"),
    path("payment/", payment, name="payment"),
    path("success/", success, name="success"),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls'))
]+ static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)


# urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

project/app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Course(models.Model):
    name=models.CharField(max_length=30,null=False)
    slug=models.CharField(max_length=30,null=True,unique=True)
    description=models.CharField(max_length=30,null=True)
    price=models.IntegerField(null=False)
    discount=models.IntegerField(null=False,default=0)
    active=models.BooleanField(default=False)
    date=models.DateTimeField( auto_now_add=True)
    thumbnail=models.ImageField(upload_to="thumbnail/")
    resource=models.FileField( upload_to="resource/")
    course_length=models.IntegerField(null=False)

    def __str__(self):
        return self.name


class CourseProperty(models.Model):
    description=models.CharField(max_length=30,null=False)
    course=models.ForeignKey(Course,on_delete=models.CASCADE)

    class Meta:
        abstract = True                         # Abstract does not create a class CourseProperty.
        

# _____inherit the CoursePropeerty____

class Tag(CourseProperty):
    pass


class Prerequisite(CourseProperty):
    pass

class Learning(CourseProperty):
   pass



class Video(models.Model):
    title=models.CharField(max_length=128,null=False)
    course=models.ForeignKey(Course,on_delete=models.CASCADE)
    serial_number=models.IntegerField(null=False)
    video_id = models.FileField(upload_to="video/")
    is_preview=models.BooleanField(default=False)

    def __str__(self):
        return self.title
    

class UserCourse(models.Model):
    
    user=models.ForeignKey(User,null=False,on_delete=models.CASCADE)
    course=models.ForeignKey(Course,null=False,on_delete=models.CASCADE)
    date=models.DateTimeField( auto_now_add=True)

    def __str__(self):
        return f'{self.user} - {self.course.name}'
    


class Payment(models.Model):
    
    order_id=models.CharField( max_length=50,null=False)
    payment_id=models.CharField( max_length=100)
    user_course=models.ForeignKey(UserCourse,null=True, blank=True ,on_delete=models.CASCADE)
    user=models.ForeignKey(User,null=False,on_delete=models.CASCADE)
    course=models.ForeignKey(Course,null=False,on_delete=models.CASCADE)
    date=models.DateTimeField( auto_now_add=True)
    status=models.BooleanField(default=False)

 

project/app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseBadRequest
from .models import *
from django.contrib.auth.forms import UserCreationForm
import razorpay
from django.views.decorators.csrf import csrf_exempt

# Create your views here


def home(request):
    obj = Course.objects.all()
    return render(request, "home.html", {"obj": obj})


def coursepage(request, slug):
    print(request.user)
    course = Course.objects.get(slug=slug)
    serial_number = request.GET.get("lecture")
    if serial_number is None:
        serial_number = 1
    video = Video.objects.get(serial_number=serial_number, course=course)
    if (request.user.is_authenticated is False) and (video.is_preview is False):
        return redirect("login")

    print(serial_number)
    context = {
        "course": course,
        "video": video,
    }
    return render(request, "course_page.html", context=context)


# user Login Signup
def signup(request):
    if request.method == "GET":
        form = UserCreationForm()
    return render(request, "signup.html", {"form": form})


def login(request):
    return render(request, "login.html")


# client = razorpay.Client(auth=("rzp_test_ank5gb82ed6Jfx","jPpRlGXIaMvgyrlcb1gXuEoV"))


def check_out(request, slug):
    course = Course.objects.get(slug=slug)
    if not request.user.is_authenticated:
        return redirect("login")

    action = request.GET.get("action")
    if action == "create_payment":
        amount = int(
            (course.price - (course.price * course.discount * 0.01)) * 100
        )  # Convert to paise
        context = {
            "course": course,
            "amount": amount,
        }
        return render(request, "check-out.html", context=context)
    else:
        context = {
            "course": course,
        }
        return render(request, "check-out.html", context=context)


def payment(request):
    if request.method == "POST":
        # course_id = request.POST.get("course")
        # amount = request.POST.get("amount")
        amount = float(539) * 100
        print(amount)
        course = Course.objects.get(name="Html")
        if not course or not amount:
            return HttpResponseBadRequest("Course and amount are required fields.")

        try:
            client = razorpay.Client(
                auth=("rzp_test_AcIEh6rX45zRp8", "alxj2MIEOtVrhPpGGbMyFvmX")
            )
            response_payment = client.order.create(
                {
                    "amount": amount,
                    "currency": "INR",  # Use a supported currency like INR
                    "payment_capture": "1",
                }
            )
        except razorpay.errors.BadRequestError as e:
            return HttpResponseBadRequest(f"Bad Request: {str(e)}")
        except razorpay.errors.ServerError as e:
            return HttpResponse("Server Error: Please try again later.", status=500)

        order_status = response_payment["status"]
        payment_id = response_payment["id"]
        print(
            response_payment["amount"],
            response_payment["currency"],
            response_payment["id"],
        )
        if order_status == "created":
            # product = Payment(name=course.name, price=amount, payment_id=payment_id)
            # product.save()
            response_payment["name"] = course.name

            return render(request, "payment.html", {"payment": response_payment})
    else:

        return render(request, "payment.html")


@csrf_exempt
def success(request):
    # print(request.POST)
    if request.method == "POST":
        response = request.POST
        print(response)
        params_dict = {
            "razorpay_order_id": response["razorpay_order_id"],
            "razorpay_payment_id": response["razorpay_payment_id"],
            "razorpay_signature": response["razorpay_signature"],
        }

        # client instance
        client = razorpay.Client(
            auth=("rzp_test_AcIEh6rX45zRp8", "alxj2MIEOtVrhPpGGbMyFvmX")
        )

        try:
            status = client.utility.verify_payment_signature(params_dict)

            item = Payment.objects.get(Payment_id=response["razorpay_order_id"])
            item.razorpay_payment_id = response["razorpay_payment_id"]
            item.paid = True
            item.save()
            print("save all data in model")
            card = request.session["card"]
            card.clear()
            request.session["card"] = card
            print(status)
            return render(request, "success.html", {"status": True})
        except:
            print("Not save all data in model")
            return render(request, "success.html", {"status": False})

    return render(request, "success.html")

project/app/templates/base.html
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />

    <title>Hello, world!</title>

  </head>
  <body>
    <div>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
              <a class="navbar-brand" href="/">Navbar</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNav">
                <!-- Left -->
                <ul class="navbar-nav ">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/">Home</a>
                  </li>
                  
                </ul>

                <!-- Right -->

                <ul class="navbar-nav ml-auto">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/login">Login</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link"  aria-current="page" href="/signup">SignUp</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="/Logout">Logout</a>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
    </div>

    {% block content %} {% endblock %} 

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

project/app/templates/check-out.html
{% extends "base.html" %}
{% load custom_tag %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript %}


{% block content %}


        <div class="row">
            <br>
            {% if order is not None %}
            <h1 class="display-3">Showing Model</h1>
            {% endif %}
            <br>
            <div class="col mx-auto">
                <div class="card ml-auto" style="width: 18rem;">
                    <img src="{{course.thumbnail.url}}" class="card-img-top" alt="...">
                    <div class="card-body">
                      <h5 class="card-title">{{course.name}}</h5>
                      <p class="card-text m-0 p-0">{{course.description}}
                        <br>
                        Save{{course.discount}}%
                        <p style="font-size:20px">
                            <del>{{course.price |rupee }}</del>
                            &nbsp;
                            <span>{% cal_sellprice  course.price course.discount as value %}{{value|rupee}}</span>
                        </p>
                        </p>
                    </div>
                    <div class='card-footer p-0 border-0'>
                        <div class='row no-gutters'>
                            <div class='col border-right-1'><a href="/check-out/{{course.slug}}" class='btn btn-light btn-block'>Enroll Now</a></div>
                            <div class='col border-left-1'><a href="/course/{{course.slug}}" class='btn btn-light btn-block'>Show More</a></div>
                        </div>

                    </div>
                </div>
            </div>

          <div class='col'>
            <div>
                <p class='display-4'>{{course.name}}</p>
                <hr>
                <p class='display-5'>Payable Amount :<b>{% cal_sellprice  course.price course.discount as value %}{{value|rupee}}</b>
                </p>
                {% comment %} <a  class = "btn btn-light border" href="{% url "payment" %}">continue to pay</a> {% endcomment %}
                <form action="{% url "payment" %}" method="POST">
                    {% csrf_token %}
                    <input type="text" name="amount" value="{% cal_sellprice  course.price course.discount as value %}{{value}}">
                    <button type="submit">proceed</button>
                </form>
            </div>
          </div>
            

             

        </div>

{% endblock %}

project/app/templates/course_page.html
{% extends "base.html" %}
{% load static %}
{% load custom_tag %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static "../static/css/style.css" %}">
</head>
<body>

    {% block content %}
    
    <div class="container-fluid">
         <div>
                    <br>
                    <br>
                        <div class="card p-3">
                            <div class="row">
                                <!--  Youtube Player -->
                                <div class="col">
                                    <div class="mx-auto">
                                        <video controls id ="player" width='100%'>
                                        <source src="{{video.video_id.url}}" type="video/mp4">
                                        </video>
                                    </div>
                                </div>
                                <!--  Youtube Player  end-->
                                <!--  videos List -->
                                <div class="col-3">
                                
                                    <ul id = "video_list" class="list-group" style="overflow-y:scroll;">
                                        {% for v in course.video_set.all %}
                                        <li class="list-group-item  {% if v == video %}  active {% endif %}"><a href="?lecture={{v.serial_number}}">{{v}}</a></li>
                                        {% endfor %}
                                     </ul>
                                   
                                </div>
                        </div>
                        
                        </div>


                        <!-- Course Detail-->

                                <!--  Leacture List -->
                                <div class="mt-3">
                                    <div>
                                        <div class="card">
                                            <div class="card-body">
                                              <h5 class="card-title">{{course.name}}</h5>
                                              <p class="card-text">{{course.description}}</p>
                                              
                                            </div>
                                          </div>
                                    </div>
                                    
                                </div>

                                  <!--  Prerequisite Card   -->
                                <div class="mt-3">
                                    <div>
                                        <div class="card">
                                            <div class="card-body">
                                              <h5 class="card-title">Prerequisite</h5>
                                              <p class="card-text">
                                                    {% for pre in course.prerequisite_set.all %}
                                                    <li class=" ">{{pre.description}}</li>
                                                    {% endfor %}
                                              </p>
                                              
                                            </div>
                                          </div>
                                    </div>
                                    <!-- Prerequisite end -->

                                    <!-- Learning Card -->
                                <div class="mt-3">
                                    <div>
                                        <div class="card">
                                            <div class="card-body">
                                              <h5 class="card-title">Learning</h5>
                                              <p class="card-text">
                                                    {% for pre in course.learning_set.all %}
                                                    <li class=" ">{{pre.description}}</li>
                                                    {% endfor %}
                                              </p>
                                              
                                            </div>
                                          </div>
                                    </div>
                                    <!-- Learning end -->
                                </div>
                </div>
    </div>

    <script>
        var player;
        var video_list
          {% comment %} window.onload = ()=>{
            player = document.getElementById('player')
            maintaneRatio() 
        } {% endcomment %}
        
        document.onreadystatechange = function(){
            if(document.readyState == 'interactive'){
                player = document.getElementById('player')
                video_list = document.getElementById('video_list')
                maintaneRatio()
            }
        }
        function maintaneRatio(){
            var w = player.clientWidth
            var h = (w*9)/16
            console.log(w,h)
            player.height = h
            video_list.style.maxHeight = h +"px"
        }
    
        window.onresize = maintaneRatio 
    </script>
    {% endblock %}


</body>
</html>

project/app/templates/home.html
{% extends "base.html" %}
{% load custom_tag %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    {% block content %}
    
    <div class="container-fluid">
          <div class="row">
                {% for i in obj %}
                <div class="col mx-auto">
                    <div class="card mx-auto" style="width: 18rem;">
                        <img src="{{i.thumbnail.url}}" class="card-img-top" alt="...">
                        <div class="card-body">
                          <h5 class="card-title">{{i.name}}</h5>
                          <p class="card-text m-0 p-0">{{i.description}}
                            <br>
                            Save{{i.discount}}%
                            <p style="font-size:20px">
                                <del>{{i.price |rupee }}</del>
                                &nbsp;
                                <span>{% cal_sellprice  i.price i.discount as value %}{{value|rupee}}</span>
                            </p>
                            </p>
                        </div>
                        <div class='card-footer p-0 border-0'>
                            <div class='row no-gutters'>
                                <div class='col border-right-1'><a href="/check-out/{{i.slug}}" class='btn btn-light btn-block'>Enroll Now</a></div>
                                <div class='col border-left-1'><a href="/course/{{i.slug}}" class='btn btn-light btn-block'>Show More</a></div>
                            </div>

                        </div>
                    </div>
                </div>
                {% endfor%} 
                

          </div>          
                         
    </div>

    {% endblock %}


</body>
</html>

project/app/templates/login.html
{% extends "base.html" %}
{% load custom_tag %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        * {box-sizing: border-box}

/* Full-width input fields */
  input[type=text], input[type=password] {
  width: 100%;
  padding: 15px;
  margin: 5px 0 22px 0;
  display: inline-block;
  border: none;
  background: #f1f1f1;
}

input[type=text]:focus, input[type=password]:focus {
  background-color: #ddd;
  outline: none;
}
h1{
    margin:auto;
    text-align:center;
}
p{
    margin:auto;
    text-align:center;
    margin-top:20px;
}
hr {
  border: 1px solid #f1f1f1;
  margin-bottom: 25px;
}

/* Set a style for all buttons */
button {
  background-color: #04AA6D;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
  opacity: 0.9;
  border-radius: 20px;
  margin-left:20vw;
}

button:hover {
  opacity:1;
}

/* Extra styles for the cancel button */
.cancelbtn {
  padding: 14px 20px;
  background-color: #f44336;
}

/* Float cancel and signup buttons and add an equal width */
.cancelbtn, .signupbtn {
  float: left;
  width: 50%;
}

/* Add padding to container elements */
.container {
  padding: 16px;
}

/* Clear floats */
.clearfix::after {
  content: "";
  clear: both;
  display: table;
}

/* Change styles for cancel button and signup button on extra small screens */
@media screen and (max-width: 300px) {
  .cancelbtn, .signupbtn {
    width: 100%;
  }
}
    </style>
</head>
<body>
    <form action="" style="border:1px solid #ccc">
        <div class="container">
          <h1>Login</h1>
          <hr>
      
          <label for="email"><b>Email</b></label>
          <input type="text" placeholder="Enter Email" name="email" required>
      
          <label for="psw"><b>Password</b></label>
          <input type="password" placeholder="Enter Password" name="psw" required>

          <div class="clearfix">
            {% comment %} <button type="button" class="cancelbtn">Cancel</button> {% endcomment %}
            <button type="submit" class="signupbtn">Sign Up</button>
          </div>
          <p>Dont have an account <a href="{% url "signup" %}" style="color:dodgerblue">Register Now</a>.</p>
        </div>
      </form>
</body>
</html>



{% endblock%}

project/app/templates/payment.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
      integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
      integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
      crossorigin="anonymous"
    ></script>
  </head>
  <body>
    {% comment %}
    <form method="post">
      {% csrf_token %}
      <table>
        {{form}}
      </table>
      <button type="submit">Buy</button>
      <br /><br />
    </form>
    {% endcomment %}
    <form action="{% url 'success' %}" method="post">
      {% csrf_token %}
      <script
        src="https://checkout.razorpay.com/v1/checkout.js"
        data-key="rzp_test_AcIEh6rX45zRp8"
        data-amount="{{payment.amount}}"
        data-currency="{{payment.currency}}"
        data-order_id="{{payment.id}}"
        data-buttontext="Pay with Razorpay"
        data-name="Item Corp"
        data-description="A Wild Sheep Chase is the third novel by Japanese author Haruki Murakami"
        data-image="https://example.com/your_logo.jpg"
        data-prefill.name="adhiraj"
        data-prefill.email="neeraj.patel@gmail.com"
        data-theme.color="#1d9284"
      ></script>
      <input type="hidden" custom="Hidden Element" name="hidden" />
    </form>
  </body>
</html>

project/app/templates/signup.html
{% extends "base.html" %}
{% load custom_tag %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript %}


{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        * {box-sizing: border-box}

/* Full-width input fields */
  input[type=text], input[type=password] {
  width: 100%;
  padding: 15px;
  margin: 5px 0 22px 0;
  display: inline-block;
  border: none;
  background: #f1f1f1;
}

input[type=text]:focus, input[type=password]:focus {
  background-color: #ddd;
  outline: none;
}

hr {
  border: 1px solid #f1f1f1;
  margin-bottom: 25px;
}

/* Set a style for all buttons */
button {
  background-color: #04AA6D;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
  opacity: 0.9;
}

button:hover {
  opacity:1;
}

/* Extra styles for the cancel button */
.cancelbtn {
  padding: 14px 20px;
  background-color: #f44336;
}

/* Float cancel and signup buttons and add an equal width */
.cancelbtn, .signupbtn {
  float: left;
  width: 50%;
}

/* Add padding to container elements */
.container {
  padding: 16px;
}

/* Clear floats */
.clearfix::after {
  content: "";
  clear: both;
  display: table;
}

/* Change styles for cancel button and signup button on extra small screens */
@media screen and (max-width: 300px) {
  .cancelbtn, .signupbtn {
    width: 100%;
  }
}
    </style>
</head>
<body>
    <form action="" style="border:1px solid #ccc">
        <div class="container">
          <h1>Sign Up</h1>
          <p>Please fill in this form to create an account.</p>
          <hr>
      
          <label for="email"><b>Email</b></label>
          <input type="text" placeholder="Enter Email" name="email" required>
      
          <label for="psw"><b>Password</b></label>
          <input type="password" placeholder="Enter Password" name="psw" required>
      
          <label for="psw-repeat"><b>Repeat Password</b></label>
          <input type="password" placeholder="Repeat Password" name="psw-repeat" required>
      
          <label>
            <input type="checkbox" checked="checked" name="remember" style="margin-bottom:15px"> Remember me
          </label>
      
          <p>By creating an account you agree to our <a href="#" style="color:dodgerblue">Terms & Privacy</a>.</p>
      
          <div class="clearfix">
            {% comment %} <button type="button" class="cancelbtn">Cancel</button> {% endcomment %}
            <button type="submit" class="signupbtn">Sign Up</button>
          </div>
        </div>
      </form>
</body>
</html>
{% endblock %}

project/app/templates/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Order Success</title>
    <link rel="stylesheet" href="styles.css">
    <style>
        body {
    font-family: Arial, sans-serif;
    margin: 0;
    padding: 0;
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
    background-color: #f0f0f0;
}

.container {
    text-align: center;
    background-color: #fff;
    padding: 20px;
    border-radius: 5px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
}

button {
    padding: 10px 20px;
    background-color: #007bff;
    color: #fff;
    border: none;
    border-radius: 5px;
    cursor: pointer;
    transition: background-color 0.3s ease;
}

button:hover {
    background-color: #0056b3;
}

    </style>
</head>
<body>
    <div class="container">
        <h1>Order Successful</h1>
        <p>Your order has been successfully placed.</p>
        <p>Thank you for shopping with us!</p>
        <a href="{% url "home" %}">Back to cart</a>
    </div>



</body>
</html>